apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: mai-assistant-rabbitmq
requires:
  - path: namespace.yaml
  - path: secrets.yaml
deploy:
  helm:
    releases:
      - name: rabbitmq
        remoteChart: oci://registry-1.docker.io/bitnamicharts/rabbitmq
        upgradeOnChange: true
        createNamespace: true
        namespace: mai-assistant
        valuesFiles:
          - ../.helm/rabbitmq/values.yaml
portForward:
  - resourceType: service
    resourceName: rabbitmq
    namespace: mai-assistant
    port: 5672 # RabbitMQ
  - resourceType: service
    resourceName: rabbitmq
    namespace: mai-assistant
    port: 15672 # RabbitMQ Management UI