apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: wizard-ai-redis
requires:
  - path: namespace.yaml
  - path: secrets.yaml
deploy:
  helm:
    releases:
      - name: redis
        remoteChart: oci://registry-1.docker.io/bitnamicharts/redis
        upgradeOnChange: true
        createNamespace: true
        namespace: wizard-ai
        valuesFiles:
          - ../.helm/redis/values.yaml
portForward:
  - resourceType: service
    resourceName: redis-master
    namespace: wizard-ai
    port: 6379