apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-custom
  namespace: mai-assistant
type: Opaque
data:
  rabbitmq-password: cGFzc3dvcmQ= # password
  rabbitmq-erlang-cookie: cGFzc3dvcmQ= # password