apiVersion: v1
kind: Service
metadata:
  name: wizard-ai-telegram-bot-service
  namespace: wizard-ai
spec:
  selector:
    app: wizard-ai-telegram-bot
  ports:
    - name: debug
      protocol: TCP
      port: 5679
      targetPort: 5678