site_name: MAI Assistant
theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: ['../wizard_ai']

plugins:
- search
- gen-files:
    scripts:
    - scripts/gen_ref_pages.py  
- literate-nav:
    nav_file: SUMMARY.md
- mkdocstrings

nav:
  - Code Reference: reference/