name: Docker Image CI

on:
  push:
    branches: 
    - "main"
  pull_request:
    branches: 
    - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for wizard_ai
      run: docker build . --file .docker/wizard_ai.Dockerfile --tag wizard_ai:$(date +%s) --build-arg BUILD_TYPE=production
    - name: Build the Docker image for wizard_ai_telegram_bot
      run: docker build . --file .docker/wizard_ai_telegram_bot.Dockerfile --tag wizard_ai_telegram_bot:$(date +%s) --build-arg BUILD_TYPE=production