name: Linter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies [mai-assistant]
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        cd mai_assistant
        poetry install --with lint
    - name: Analysing the code with pylint
      run: |
        cd mai_assistant
        poetry run python -m pylint $(git ls-files '*.py') --rcfile=../pylint.rc --fail-under=8
    - name: Installing dependencies [mai-assistant-telegram-bot]
      run: |
        cd mai_assistant_telegram_bot
        poetry install --with lint
    - name: Analysing the code with pylint [mai-assistant-telegram-bot]
      run: |
        cd mai_assistant_telegram_bot
        poetry run python -m pylint $(git ls-files '*.py') --rcfile=../pylint.rc --fail-under=8