name: Auto Doc Generation

on:
  workflow_dispatch:
    inputs:
      scan-dir:
        type: string
        description: 'The directory to scan for doc generation'

jobs:
  auto_doc_generation:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Docs
        uses: gianfrancodemarco/zero-docs-action@main
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          paths: ${{ github.event.inputs.scan-dir }}
          reviewers: gianfrancodemarco
